# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfa23d2b3c6acac218dc6a929925a202938c9503512509fa0d72210a82ae358d9b25fedb13f82af06fdc51ad63f506c35dc4c4b5aac0a0b833bfd95703429e42

test:
  secret_key_base: bb531481fbf66015105e81b3390ede01c6cb8acdfd9919d3b871c1de1543230eea68914633e3387375ad2ebc60c4df60760c037dc14e8e76dcf230b2cf726b56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
